#+STARTUP: hidestars
* LED Assignments
** Start by building the circuit.  In the Adeept wiring folder there is a 
   'png', in there is 01_led.png. 

** Next try running the 01_blinkingLed_0.py and 01_blinkingLed_1.py programs
   from shell.  Read through each program, and recall that only the lines 
   that DO NOT start with '#' are python commands/code.  Everything else 
   is notes explaining what is going on.

** Questions
*** (1) In 01_blinkingLed_0.py, we had the command myLed.blink(2) or similar
    with some other number in place of 2.  What exactly does the 2 do? Does 
    it control how long the LED is on? Or off? Or both?  Experiment as needed 
    to find out.
*** (2) When building LED circuits on the breadboard without Python, the only 
    way we could make an LED blink was by wiring in a button and pressing it 
    on/off to close the circuit.  Describe what you think myLed.blink(2) is 
    "doing" to make the light go on and off.
*** (3) Examine the wiring setup on your breadboard.  Recall when building 
    circuits we would connect power (3V) to the power rail, run that through the 
    resistor and LED, and then return the current to the negative power rail and 
    connect that to ground. What is different in this case? Where is the ground? 

  
